### ISSUE TITLE
forgotten in the documentation part, in the text to paste in configuration.yaml .  ( input_name2 "bing_text2" )

### ISSUE THREAD

**Issue by dextouu** [tiernan1979/BingChatAI#3]
hello, on the documentation, there was a forgotten colon and underscore  in the sensor .
```
input_text:
  gpt_prompt:
    initial: ""
    max: 255
  gpt_prompt2:
    initial: ""
    max: 255
## This is the input_text entity you'll use to send prompts.

sensor:
  - platform: BingChatAI
    name: "BingChatAI"
## Optional. Defaults to BingChatAI
    input_name: "bing_text"
    input_name2 "bing_text2"     <---------------------------   # corrected version : input_name_2: "bing_text2"
## Optional. Defaults to bing_text. This is your input_text name
    style: "Precise"
## Optional. Defaults to Precise. This is the search Style
```
